_target_: gem.pipeline.gem_pipeline.Pipeline
args_denoiser3d: ${network}
args:
  train_modes: ["regression"]
  endecoder_opt: ${endecoder}
  use_regression_outputs_prob: 0.
  use_cfg_sampler_for_gen: true
  inpaint_x_start_gt: false
  regression_only: true
  encoded_music_dim: 35
  multicond_args: ${multicond_args}
  infer_version: 2
  weights:
    simple: 1.
    cr_j3d: 0.
    transl_c: 0.
    cr_verts: 0.
    j2d: 0.
    j2d_17: 0.
    verts2d: 0.
    transl_w: 1.
    static_conf_bce: 1.

  static_conf:
    vel_thr: 0.15

  in_attr:
    - f_imu
  mask_out_attr: []
  out_attr: []
