# @package _global_
defaults:
  - /diffusion@model_cfg.diffusion: ddim
  - override /data: mocap/trainX_testY
  - override /model: gem
  - override /network: diffusion_lg
  - override /pipeline: dual_mode
  - override /endecoder: v1_smpl_amass_bedlam
  - override /optimizer: adamw_2e-4
  - override /scheduler: epoch_half_500_750
  - override /train_datasets:
      - amass_v11
      - bedlam_v2
      - h36m_v1
      - 3dpw_v1
      - aistpp_train
      - beat2_static_train
      - humanml3d_static_train
      - 3dpw_occ_v1
  - override /test_datasets:
      - emdb1_v1_fliptest
      - emdb2_v1_fliptest
      - 3dpw_fliptest
      - rich_all
  - override /callbacks:
      - ckpt_saver/every10000s_top100
      - prog_bar/prog_reporter_ed1
      - train_speed_timer/base
      - lr_monitor/pl
      - metric/metric_emdb1
      - metric/metric_emdb2
      - metric/metric_3dpw
      - vis/vis_text
      - metric/metric_rich
      - metric/metric_3dpw_occ
  - _self_

exp_name_base: ${hydra:runtime.choices.exp}
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: gem_mixed

train_datasets:
  aistpp_train:
    feat_version: v2

multicond_args: null

model:
  model_cfg:
    body_model: smplx

    text_encoder:
      load_llm: false
      llm_version: "t5-3b"
      max_text_len: 50

    condition_mask:
      mask_img_prob: 0.5
      mask_cam_prob: 1.0
      reuse_regression_mask: false
      regression_no_img_mask: true

    mask_cfg:
      drop_prob: 0.75
      max_num_drops: 3
      min_drop_nframes: 1
      max_drop_nframes: 30
    body_mask_cfg:
      drop_prob: 0.75
      joint_drop_prob: 0.25
      max_num_drops: 3
      min_drop_nframes: 1
      max_drop_nframes: 30
    music_mask_prob: 0.1
    audio_mask_prob: 0.1

network:
  model_cfg:
    regression_only: false
    denoiser:
      args: ${pipeline.args}
      encode_text: true
      encoded_text_dim: 1024
      text_encoder_cfg:
        mode: all
        cross_attn_type: mha

pipeline:
  args:
    extract_features: false
    regression_only: false

data:
  loader_opts:
    train:
      batch_size: 128
      num_workers: 6

pl_trainer:
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: null
  check_val_every_n_epoch: null
  val_check_interval: 3000
  max_steps: 500000
  devices: 1

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "gem"
  save_dir: "/tmp"
  name: ""
  version: ""
  resume: "allow"
  dir: "/tmp"
  id: null

use_wandb: true
