# @package _global_
defaults:
  - /diffusion@model_cfg.diffusion: ddim
  - override /data: mocap/trainX_testY
  - override /model: gem
  - override /network: diffusion
  - override /pipeline: regression_only
  - override /endecoder: v1_smpl_amass_bedlam
  - override /optimizer: adamw_2e-4
  - override /scheduler: epoch_half_200_350
  - override /train_datasets:
      - amass_v11
      - bedlam_v2
      - h36m_v1
      - 3dpw_v1
  - override /test_datasets:
      - emdb1_v1_fliptest
      - emdb2_v1_fliptest
      - 3dpw_fliptest
  - override /callbacks:
      - ckpt_saver/every10000s_top100
      - prog_bar/prog_reporter_ed1
      - train_speed_timer/base
      - lr_monitor/pl
      - metric/metric_emdb1
      - metric/metric_emdb2
      - metric/metric_3dpw
  - _self_

exp_name_base: ${hydra:runtime.choices.exp}
exp_name_var: ""
exp_name: ${exp_name_base}_${exp_name_var}
data_name: gem_mixed

multicond_args: null

pl_trainer:
  precision: 16-mixed
  log_every_n_steps: 10
  gradient_clip_val: 0.5
  max_epochs: null
  check_val_every_n_epoch: null
  val_check_interval: 3000
  max_steps: 500000
  devices: 1

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "gem"
  save_dir: "/tmp"
  name: ""
  version: ""
  resume: "allow"
  dir: "/tmp"
  id: null

use_wandb: true

model:
  model_cfg:
    body_model: smplx

network:
  model_cfg:
    regression_only: true
    denoiser:
      args: ${pipeline.args}
      encode_text: false
      encoded_text_dim: 1024
      text_encoder_cfg:
        mode: none
        cross_attn_type: mha

pipeline:
  args:
    extract_features: false
