# @package _global_
defaults:
  - gem_imu
  - _self_

data_name: gem_imu_amass_causal

model:
  model_cfg:
    streaming:
      enable: true
      history_frames: 96
      future_frames: 24
      online_chunk_frames: 4
